#!/bin/bash
# aged - Find files sorted by timestamp metadata.
# © Mike Lalumiere 2018

# tp - time stamp
# print time with bash builtin
tp() { printf "%(${1:-%s})T\\n" "${2:--1}"; }

ti() {
    # usage
    read -r -d '' use <<EOF
USAGE: ti [OPTIONS] INTERVAL
Parse and render temporal shorthand.

UNITS:                  | SCALES:
 s : second  d : day    |  D : 10e1  M : 10e6
 m : minute  w : week   |  H : 10e2  G : 10e9
 h : hour    y : year   |  K : 10e3  T : 10e12

MODES
 -a : after     : print current time plus INTERVAL
 -b : before    : print current time minus INTERVAL
 -c : numeric   : print integer number of seconds in INTERVAL
 -d : shorthand : print string shorthand of INTERVAL

OPTIONS
 -f FORMAT : render dates with given strftime FORMAT
 -t TIME   : calculate dates relative to TIME

SAMPLE
 1d        : 86400 | 1Ms    : 1000000
 43m20s    : 2600  | 3Kh    : 259200000
 18h12m16s : 65536 | 2Gy    : 63115200000000000

EOF
    # mark current time
    local now
    now=$(tp %s)
    # scale units
    declare -A scale
    scale=(
        ["D"]=$((10**1))
        ["H"]=$((10**2))
        ["K"]=$((10**3))
        ["M"]=$((10**6))
        ["G"]=$((10**9))
        ["T"]=$((10**12))
    )
    # time units
    declare -A unit
    unit=(
        ["y"]=31557600
        ["w"]=604800
        ["d"]=86400
        ["h"]=3600
        ["m"]=60
        ["s"]=1
    )
    # reverse lookup integer on scale
    # declare -A rscale
    # for key in "${!scale[@]}"; do rscale["${scale[$key]}"]="$key"; done
    # reverse lookup integer on unit
    declare -A runit
    for key in "${!unit[@]}"; do runit["${unit[$key]}"]="$key"; done
    # accept options
    local mode="" fmt="%s" when="$now"
    local opt OPTIND OPTARG
    while getopts ":abcdf:hs:t:u:" opt; do
        case "$opt" in
            a) mode=1           ;; # output date after given interval
            b) mode=2           ;; # output date before given interval
            c) mode=3           ;; # output number of seconds in given interval
            d) mode=4           ;; # output shorthand string for given interval
            f) fmt="$OPTARG"    ;; # set format string for date output
            t) when="$OPTARG"   ;; # set relative unix timestamp for date calculation
            h) # help
                printf "%s\\n" "$use" >&2
                return
                ;;
            ?) # invalid?
                printf "Invalid option '%s'\\n%s\\n" "$OPTARG" "$use" >&2
                return 1
                ;;
        esac
    done
    shift $((OPTIND - 1))
    # accept arguments
    local inp="$*"
    if [ -z "$inp" ]; then
        printf "%s\\n" "$use" >&2
        return
    fi
    # infer mode if not specified
    if [ -z "$mode" ]; then
        if [[ "$inp" =~ ^[:digit:]+$ ]]; then
            mode=4
        else
            mode=3
        fi
    fi
    # decode input string into integer seconds
    local num="" char="" secs=0 mul=1 idx=0
    for ((idx=0; idx<="${#inp}"; idx++)); do
        char="${inp:$idx:1}"
        case "$char" in
            [[:digit:]]) # accumulate digits
                num="${num}${char}"
                ;;
            ["$(printf "%s" "${!scale[@]}")"]) # scale unit
                mul="${scale[$char]}"
                (( idx++ ))
                char="${inp:$idx:1}"
                ;&
            ["$(printf "%s" "${!unit[@]}")"]) # time unit
                if [ -z "$char" ] || [ -z "${unit[$char]+exists}" ] ; then
                    printf "Expected time unit not '%s' at index '%d'.\\n" "$char" "$idx" >&2
                    return 2
                fi
                num="${num:-1}"
                secs=$(( secs + (num * mul * unit["$char"]) ))
                num=""
                mul=1
                ;;
            ?) # dunno
                printf "Failed to parse character '%s' at '%d'.\\n" "$char" "$idx" >&2
                return 2
            ;;
        esac
    done <<< "$inp"
    if [ -n "$num" ]; then secs=$(( secs + num )); fi
    # encode an interval string
    local tstr="" left="$secs" per=0
    while read -r val; do
        per=$((left / val))
        left=$((left % val))
        if [[ "$per" -eq 0 ]]; then continue; fi
        tstr+="${per}${runit[$val]}"
    done < <(printf "%s\\n" "${unit[@]}" | sort -r -n)
    # output depends on mode
    case "$mode" in
        1) tp "$fmt" $(( when + secs )) ;;
        2) tp "$fmt" $(( when - secs )) ;;
        3) printf "%d\\n" "$secs" ;;
        4) printf "%s\\n" "$tstr" ;;
    esac
}

aged() {
    # usage
    read -r -d '' use <<EOF
USAGE: aged [OPTIONS] [TARGET ...]
List files and directories sorted by file system timestamp metadata.

OPTIONS:
 -a -c -m    : Sort by time last of access, change, or modification.
 -d          : Limit results to directories.
 -f          : Limit results to files.
 -l          : Include columns for date and time.
 -n NUMBER   : List only the first NUMBER lines.
 -r          : Reverse sort order, newest files first.
 -p GLOB     : Print only files matching GLOB.
 -y INTERVAL : Show files younger than INTERVAL.
 -z INTERVAL : Show files older than than INTERVAL.

EXAMPLES:
$ aged -n1; aged -r -n1
  Show the least and most recently accessed file here.
$ aged -m -l -r -n10 ~/foo
  Show the path and timestamp of the ten most recently modified files "~/foo".
$ aged -m -z 2d -y 3w
  Show files modified more than two days but less than three weeks ago.
$ feh -Z -f <(aged -a -n6 -p '*.jpg' ~/img/)
  View the six least recently accessed JPEGs in the given directory.
$ mpv \$(aged -m -p '*.ogg' -n1 ~/videos/)
  Play the oldest OGG video in the given directory.
$ aged -m -y 30d ./quux.conf || echo "not recently"
  Check if a file has been modified within 30 days.
EOF
    # check requirements
    if ! type sort find &>/dev/null; then
        echo "Core utilities find and sort are required!" >&2
        return 255
    fi
    # accept options
    local mode=1 num=0  old='' yng='' kind pat rev long
    local opt OPTIND OPTARG
    while getopts ":acdfhmn:p:rly:z:" opt; do
        case "$opt" in
            # sort mode
            a) mode=1        ;; # consider atime
            c) mode=2        ;; # consider ctime
            m) mode=3        ;; # consider mtime
            d) # find only directories
                kind='d'
                ;;
            f) # find only files
                kind='f'
                ;;
            n) # first N lines
                num="$OPTARG"
                if ! [[ "$num" =~ ^[0-9]+$ ]]; then
                    printf "Argument to -n must be a number!\\n" >&2
                    return 3
                fi
                ;;
            p) # file glob pattern
                pat="$OPTARG"
                ;;
            l) # output long details
                long="yes"
                ;;
            r) # reverse output sort by age
                rev="yes"
                ;;
            y) # select files younger than the given interval
                if ! yng=$(ti -b "$OPTARG"); then
                    printf "Could not parse '%s' as a time interval.\\n" "$OPTARG" >&2
                    return 3
                fi
                ;;
            z) # select files older than than the given interval
                if ! old=$(ti -b "$OPTARG"); then
                    printf "Could not parse '%s' as a time interval.\\n" "$OPTARG" >&2
                    return 3
                fi
                ;;
            h) # help
                printf "%s\\n" "$use" >&2
                return
                ;;
            \?) # invalid option
                printf "Bad option: -%s.\\n\\n%s\\n" "$OPTARG" "$use" >&2
                return 2
                ;;
        esac
    done
    shift $((OPTIND - 1))
    # accept target arguments
    declare -a tgts
    for tgt in "$@"; do
        if ! [ -e "$tgt" ]; then
            printf "'%s' does not exist\\n%s\\n" "$tgt" "$use" >&2
            return 3
        else
            tgts+=("$tgt")
        fi
    done
    # by default search the current directory
    if ! (( ${#tgts[@]} )); then
        tgts+=(".")
    fi
    # output paths with find stat: atime mtime ctime path
    local ind=0
    while read -r a c m f && [[ "$num" == 0 || "$ind" -lt "$num" ]]; do
        # determine current time
        declare -a when
        when=(" " "$a" "$c" "$m")
        # determine current time
        local now time since
        now=$(tp %s)
        time="${when[$mode]}"
        since=$((now - time))
        # filter results maybe
        if [ -n "$yng" ] && [[ "$yng" -gt "$time" ]]; then continue; fi
        if [ -n "$old" ] && [[ "$old" -lt "$time" ]]; then continue; fi
        # output long or short
        if [ -n "$long" ]; then
            printf "%(%F %T)T %s %s\\n" "$time" "$(ti -d "$since")" "$f"
        else
            printf "%s\\n" "$f"
        fi
        # count a result
        (( ind++ ))
    done < <(eval find "${tgts[@]@Q}" \
                  "${kind+-type \"\$kind\"}" \
                  "${pat+-iname \"\$pat\"}" \
                  '-printf "%As %Cs %Ts %p\n"' \
                 | eval sort "${rev+-r}" -n -k "$mode")
    # success if any results found
    (( ind > 0 ))
}
# run it unless sourced
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then aged "$@"; fi
